# Generated by Django 5.2 on 2025-04-30 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_app', '0002_memory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='location',
        ),
        migrations.AddField(
            model_name='memory',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memory',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
